### ISSUE TITLE
python 2.7 import error

### ISSUE THREAD

**Issue by trey-stafford** [conda-forge/flake8-feedstock#42]
Issue:
In python 2.7, flake8 v3.8.1 fails with an import error related to the `typing` module.
```
$ flake8 --config .flake8rc $(find . -name '*.py') --verbose
Traceback (most recent call last):
  File "/home/trst2284/miniconda3/envs/test4/bin/flake8", line 6, in <module>
    from flake8.main.cli import main
  File "/home/trst2284/miniconda3/envs/test4/lib/python2.7/site-packages/flake8/main/cli.py", line 3, in <module>
    from typing import List, Optional
ImportError: No module named typing

```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/trst2284/miniconda3/envs/test4:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
backports                 1.0                        py_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
configparser              4.0.2                    py27_0
contextlib2               0.6.0.post1                py_0    conda-forge
flake8                    3.8.1              pyh9f0ad1d_0    conda-forge
importlib-metadata        1.5.0            py27h8c360ce_1    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.3                  he6710b0_1
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
more-itertools            5.0.0                      py_0    conda-forge
ncurses                   6.2                  he6710b0_1
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
python                    2.7.18               h15b4118_1
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.0                  h7b6447c_0
scandir                   1.10.0           py27hdf8410d_1    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.31.1               h62c20be_1
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
zipp                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test4
    active env location : /home/trst2284/miniconda3/envs/test4
            shell level : 1
       user config file : /home/trst2284/.condarc
 populated config files : /home/trst2284/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /home/trst2284/miniconda3  (writable)
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/trst2284/miniconda3/pkgs
                          /home/trst2284/.conda/pkgs
       envs directories : /home/trst2284/miniconda3/envs
                          /home/trst2284/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-99-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/trst2284/.netrc
           offline mode : False

```
</details>

**Comment by dopplershift** [comment]
This happened because conda-forge stopped doing new builds for 2.7 and this package was converted to noarch python--eliminating the conditional dependence on `typing` and `enum34`. #45 corrects the Python dependence going forward.
